package intransix.osm.termite.gui.maplayer;

import intransix.osm.termite.render.MapLayer;
import intransix.osm.termite.render.MapPanel;

/**
 *
 * @author sutter
 */
public class MapLayerManagerPane extends javax.swing.JPanel {
	
	private MapPanel mapPanel;
	private java.util.List<MapLayer> layers;

	/**
	 * Creates new form MapLayerManagerPane
	 */
	public MapLayerManagerPane() {
		initComponents();
	}
	
	public void setMapPanel(MapPanel mapPanel) {
		 this.mapPanel = mapPanel;
	}
	
	public void setMapLayers(java.util.List<MapLayer> layers) {
		this.layers = layers;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("Map Layer Manager");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jLabel1)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addContainerGap(248, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
